#!/bin/bash

if [ "$1" == "help" ];
    then echo "Usage: ./startup_script [norun | runonly | help]"
else
    if [ "$1" != "runonly" ];
        then
        pip3 install virtualenv
        virtualenv env
        source env/bin/activate
        pip3 install -r requirements.txt
        npm install
        python3 manage.py makemigrations
        python3 manage.py migrate
    fi
    if [ "$1" == "norun" ];
        then echo "Server not starting"
    else
        echo "Server starting"
        python3 manage.py runserver &
        npm run dev &
    fi
fi