# Generated by Django 2.2.6 on 2019-10-25 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('odin_username', models.CharField(max_length=200)),
                ('psu_id', models.IntegerField(default=0)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('hire_date', models.DateField()),
                ('fte', models.IntegerField(default=0)),
                ('month_lookback_12', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('month_lookback_6', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fmla_eligibility', models.CharField(max_length=1)),
                ('ofla_eligibility', models.CharField(max_length=1)),
                ('deductions_eligibility', models.CharField(max_length=200)),
                ('protected_leave_hrs_taken', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_protected_leave_hrs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='gobeacc',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('gobeacc_username', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='goremal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goremal_id', models.IntegerField(default=0)),
                ('goremal_emal_code', models.CharField(max_length=4)),
                ('goremal_email_address', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='gorsdav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gorsdav_table_name', models.CharField(max_length=30)),
                ('gorsdav_attr_name', models.CharField(max_length=30)),
                ('gorsdav_pk_parenttab', models.CharField(max_length=512)),
                ('gorsdav_value', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='nbrbjob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbrbjob_pidm', models.IntegerField(default=0)),
                ('nbrbjob_posn', models.CharField(max_length=6)),
                ('nbrbjob_suff', models.CharField(max_length=2)),
                ('nbrbjob_contract_type', models.CharField(max_length=1)),
                ('nbrbjob_begin_date', models.DateField(blank=True, null=True)),
                ('nbrbjob_end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='nbrjobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbrjobs_pidm', models.IntegerField(default=0)),
                ('nbrjobs_posn', models.CharField(max_length=6)),
                ('nbrjobs_suff', models.CharField(max_length=2)),
                ('nbrjobs_effective_date', models.DateField()),
                ('nbrjobs_ecls_code', models.CharField(max_length=2)),
                ('nbrjobs_appt_pct', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pdrdedn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdrdedn_pidm', models.IntegerField()),
                ('pdrdedn_bdca_code', models.CharField(max_length=3)),
                ('pdrdedn_effective_date', models.DateField()),
                ('pdrdedn_status', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='pebempl',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pebempl_empl_status', models.CharField(max_length=1)),
                ('pebempl_first_hire_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='perbfml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perbfml_pidm', models.IntegerField(default=0)),
                ('perbfml_max_units', models.IntegerField(default=0)),
                ('perbfml_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='perefml',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('perefml_perbfmla_id', models.IntegerField()),
                ('perefml_earn_code', models.CharField(max_length=3)),
                ('perefml_claim_units', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='perfmla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfmla_id', models.IntegerField(default=0)),
                ('perfmla_perbfml_id', models.IntegerField()),
                ('perfmla_begin_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='perjtot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perjtot_pidm', models.IntegerField(default=0)),
                ('perjtot_earn_code', models.CharField(max_length=3)),
                ('perjtot_year', models.IntegerField()),
                ('perjtot_month', models.IntegerField()),
                ('perjtot_hrs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='perleav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perleav_pidm', models.IntegerField(default=0)),
                ('perleav_leave_code', models.CharField(max_length=4)),
                ('perleav_begin_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('perleav_accrued', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('perleav_taken', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Current_Balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='phraccr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phraccr_pidm', models.IntegerField(default=0)),
                ('phraccr_leav_code', models.CharField(max_length=4)),
                ('phraccr_curr_accr', models.IntegerField()),
                ('phraccr_activity_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ptrearn',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('ptrearn_fmla_eligible_hrs_ind', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='spriden',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('spriden_id', models.CharField(max_length=9)),
                ('spriden_last_name', models.CharField(max_length=60)),
                ('spriden_first_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Paid_leave_balances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_code', models.CharField(max_length=4)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_leaves', to='database.Employee')),
            ],
        ),
    ]
