# Generated by Django 2.2.6 on 2019-10-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gobeacc',
            fields=[
                ('gobeacc_pidm', models.IntegerField(primary_key=True, serialize=False)),
                ('gobeacc_username', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='goremal',
            fields=[
                ('goremal_pidm', models.IntegerField(primary_key=True, serialize=False)),
                ('goremal_emal_code', models.CharField(max_length=4)),
                ('goremal_email_address', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='gorsdav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gorsdav_table_name', models.CharField(max_length=30)),
                ('gorsdav_attr_name', models.CharField(max_length=30)),
                ('gorsdav_pk_parenttab', models.CharField(max_length=512)),
                ('gorsdav_value', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='nbrjob',
            fields=[
                ('nbrjob_pidm', models.IntegerField(primary_key=True, serialize=False)),
                ('nbrjob_posn', models.CharField(max_length=6)),
                ('nbrjob_suff', models.CharField(max_length=2)),
                ('nbrjob_contract_type', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='nbrjobs',
            fields=[
                ('nbrjobs_pidm', models.IntegerField(primary_key=True, serialize=False)),
                ('nbrjobs_posn', models.CharField(max_length=6)),
                ('nbrjobs_suff', models.CharField(max_length=2)),
                ('nbrjobs_effective_date', models.DateTimeField(verbose_name='date_started')),
                ('nbrjobs_ecls_code', models.CharField(max_length=2)),
                ('nbrjobs_appt_pct', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pdrdedn',
            fields=[
                ('pdrdedn_pidm', models.IntegerField(primary_key=True, serialize=False)),
                ('pdrdedn_bdca_code', models.CharField(max_length=3)),
                ('pdrdedn_effective_date', models.DateTimeField(verbose_name='effective date')),
                ('pdrdedn_status', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='pebempl',
            fields=[
                ('pebempl_pidm', models.IntegerField(primary_key=True, serialize=False)),
                ('pebempl_empl_status', models.CharField(max_length=1)),
                ('pebempl_first_hire_date', models.DateTimeField(verbose_name='date_started')),
            ],
        ),
        migrations.CreateModel(
            name='perbfml',
            fields=[
                ('perbfml_id', models.IntegerField(primary_key=True, serialize=False)),
                ('perbfml_pidm', models.IntegerField()),
                ('perbfml_max_units', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='perefml',
            fields=[
                ('perefml_id', models.IntegerField(primary_key=True, serialize=False)),
                ('perefml_perbfmla_id', models.IntegerField()),
                ('perefml_earn_code', models.CharField(max_length=3)),
                ('perefml_claim_units', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='perfmla',
            fields=[
                ('perfmla_id', models.IntegerField(primary_key=True, serialize=False)),
                ('perfmla_perbfml_id', models.IntegerField()),
                ('perfmla_begin_date', models.DateTimeField(verbose_name='begin date')),
            ],
        ),
        migrations.CreateModel(
            name='perjtot',
            fields=[
                ('perjtot_pidm', models.IntegerField(primary_key=True, serialize=False)),
                ('perjtot_earn_code', models.CharField(max_length=3)),
                ('perjtot_year', models.IntegerField()),
                ('perjtot_month', models.IntegerField()),
                ('perjtot_hrs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='perleav',
            fields=[
                ('perleav_pidm', models.IntegerField(primary_key=True, serialize=False)),
                ('perleav_leave_code', models.CharField(max_length=4)),
                ('perleav_begin_balance', models.IntegerField()),
                ('perleav_accrued', models.IntegerField()),
                ('perleav_taken', models.IntegerField()),
                ('Current_Balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='phraccr',
            fields=[
                ('phraccr_pidm', models.IntegerField(primary_key=True, serialize=False)),
                ('phraccr_leav_code', models.CharField(max_length=4)),
                ('phraccr_curr_accr', models.IntegerField()),
                ('phraccr_activity_date', models.DateTimeField(verbose_name='activity date')),
            ],
        ),
        migrations.CreateModel(
            name='ptearn',
            fields=[
                ('ptearn_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('ptearn_fmla_eligible_hrs_ind', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='spriden',
            fields=[
                ('spriden_pidm', models.IntegerField(primary_key=True, serialize=False)),
                ('spriden_id', models.CharField(max_length=9)),
                ('spriden_last_name', models.CharField(max_length=60)),
                ('spriden_first_name', models.CharField(max_length=60)),
            ],
        ),
    ]
