# Generated by Django 2.2.6 on 2019-10-16 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gobeacc',
            old_name='gobeacc_pidm',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='nbrjob',
            old_name='nbrjob_pidm',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='nbrjobs',
            old_name='nbrjobs_pidm',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='pdrdedn',
            old_name='pdrdedn_pidm',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='pebempl',
            old_name='pebempl_pidm',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='perbfml',
            old_name='perbfml_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='perefml',
            old_name='perefml_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='perfmla',
            old_name='perfmla_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='perjtot',
            old_name='perjtot_pidm',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='perleav',
            old_name='perleav_pidm',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='phraccr',
            old_name='phraccr_pidm',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='ptearn',
            old_name='ptearn_code',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='spriden',
            old_name='spriden_pidm',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='goremal',
            name='goremal_pidm',
        ),
        migrations.AddField(
            model_name='goremal',
            name='goremal_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goremal',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nbrjobs',
            name='nbrjobs_effective_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pdrdedn',
            name='pdrdedn_effective_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pebempl',
            name='pebempl_first_hire_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='perfmla',
            name='perfmla_begin_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='phraccr',
            name='phraccr_activity_date',
            field=models.DateField(),
        ),
    ]
