# Generated by Django 2.2.6 on 2019-10-30 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perleav',
            name='Current_Balance',
        ),
    ]
