# Generated by Django 2.2.7 on 2019-11-19 03:13

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_perleav_current_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_name', models.CharField(default='<built-in function id>', max_length=200)),
                ('graph_date', models.DateField(auto_now=True)),
                ('date', models.DateField(auto_now=True)),
                ('graph_data', jsonfield.fields.JSONField(null=True)),
                ('graph_cords', models.TextField(default=0)),
                ('graph_status', models.CharField(default='D', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='leavereports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leavereports_pidm', models.IntegerField()),
                ('leavereports_date', models.DateField(auto_now=True)),
                ('leavereports_report', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_classification',
            field=models.CharField(default=0.0, max_length=2),
        ),
        migrations.AddField(
            model_name='employee',
            name='graph',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='paid_leave_balances',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='reports',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fte',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='month_lookback_12',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='month_lookback_6',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='protected_leave_hrs_taken',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Paid_leave_balances',
        ),
    ]
