# Generated by Django 2.2.6 on 2019-10-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20191016_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbrjob',
            name='nbrjob_pidm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nbrjobs',
            name='nbrjobs_pidm',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nbrjob',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nbrjobs',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
