# Generated by Django 2.2.6 on 2019-10-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20191016_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdrdedn',
            name='pdrdedn_pidm',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pdrdedn',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
