# Generated by Django 2.2.6 on 2019-10-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20191016_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perbfml',
            name='perbfml_max_units',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='perbfml',
            name='perbfml_pidm',
            field=models.IntegerField(default=0),
        ),
    ]
