# Generated by Django 2.2.7 on 2019-11-20 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_remove_graph_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='graph_name',
        ),
    ]
