# Generated by Django 2.2.6 on 2019-10-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20191016_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfmla',
            name='perfmla_pidm',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='perfmla',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
