# Generated by Django 2.2.6 on 2019-10-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20191016_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbrjob',
            name='nbrjobs_begin_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='nbrjob',
            name='nbrjobs_end_date',
            field=models.DateField(null=True),
        ),
    ]
