# Generated by Django 2.2.6 on 2019-10-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20191016_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perleav',
            name='Current_Balance',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='perleav',
            name='perleav_accrued',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='perleav',
            name='perleav_begin_balance',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='perleav',
            name='perleav_taken',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
