# Generated by Django 2.2.6 on 2019-10-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20191016_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perleav',
            name='Current_Balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
