# Generated by Django 2.2.6 on 2019-10-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_auto_20191016_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perleav',
            name='Current_Balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='perleav',
            name='perleav_accrued',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='perleav',
            name='perleav_begin_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='perleav',
            name='perleav_taken',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
