# Generated by Django 2.2.6 on 2019-10-25 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_auto_20191016_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(default=0)),
                ('odin_username', models.CharField(max_length=200)),
                ('psu_id', models.IntegerField(default=0)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('hire_date', models.DateField()),
                ('fte', models.IntegerField(default=0)),
                ('max_protected_leave_hrs', models.IntegerField(default=0)),
                ('month_lookback_12', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('month_lookback_6', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fmla_eligibility', models.CharField(max_length=1)),
                ('ofla_eligibility', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Leave_balances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_code', models.CharField(max_length=4)),
                ('current_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='nbrbjob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbrbjob_pidm', models.IntegerField(default=0)),
                ('nbrbjob_posn', models.CharField(max_length=6)),
                ('nbrbjob_suff', models.CharField(max_length=2)),
                ('nbrbjob_contract_type', models.CharField(max_length=1)),
                ('nbrbjob_begin_date', models.DateField(blank=True, null=True)),
                ('nbrbjob_end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worked_hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earn_code', models.CharField(max_length=3)),
                ('hours_earned', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Employee')),
            ],
        ),
        migrations.RenameModel(
            old_name='ptearn',
            new_name='ptrearn',
        ),
        migrations.DeleteModel(
            name='nbrjob',
        ),
        migrations.RenameField(
            model_name='ptrearn',
            old_name='ptearn_fmla_eligible_hrs_ind',
            new_name='ptrearn_fmla_eligible_hrs_ind',
        ),
        migrations.AddField(
            model_name='phraccr',
            name='phraccr_pidm',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='perjtot',
            name='perjtot_hrs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='phraccr',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
