# Generated by Django 2.2.6 on 2019-10-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_auto_20191016_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perjtot',
            name='perjtot_hrs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
