# Generated by Django 2.2.6 on 2019-10-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_auto_20191016_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='phraccr',
            name='phraccr_pidm',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='phraccr',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
