# Generated by Django 2.2.6 on 2019-10-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_auto_20191016_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbrjob',
            name='nbrjobs_begin_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nbrjob',
            name='nbrjobs_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
