# Generated by Django 2.2.6 on 2019-10-25 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_auto_20191016_2234'),
        ('database', '0016_auto_20191025_0205'),
    ]

    operations = [
    ]
